### ISSUE TITLE
The action doesn't seem to be working

### ISSUE THREAD

**Issue by artemsmikh** [Axosoft/glo-action-parse-links#4]
Hey. I just tried to use this action on my repo and found out that it is not working anymore.

My goal is to move a Glo card to a column when the repo receives a push with a link to the Glo card.
The action looks like this:
```
on: push

name: Glo actions

jobs:
  build:
    name: Glo actions
    runs-on: ubuntu-latest
    steps:
    - uses: Axosoft/glo-action-parse-links@v1
      id: glo-parse

    - uses: Axosoft/glo-action-move-card@v1
      with:
        authToken: ${{ secrets.GITKRAKEN_PAT }}
        cards: '${{ steps.glo-parse.outputs.cards }}'
        column: 'Done'
      id: glo-move
```

And the link to the card looks like this:
https://app.gitkraken.com/glo/view/card/600bab2f77c640698ef00323ffaebaee

Could it be because of the link format that I believe have changed since the creation of this action?
